defaults = {
    profile = {
        nameFont = "Fonts\\FRIZQT__.TTF",
        nameFlags = "OUTLINE",
        classColorEnemyNames = false,
        classColorFriendlyNames = false,
        nameWidth = 140,
        nameFriendlyPlayerSize = 16,
        nameEnemyPlayerSize = 16,
        nameFriendlyNpcSize = 16,
        nameEnemyNpcSize = 16,
        nameAnchor = "BOTTOM",
        nameRelAnchor = "TOP",
        nameOffsetX = 0,
        nameOffsetY = 2,
        onlyNameMode = 0,
        onlyNameAnchor = "CENTER",
        onlyNameOffsetX = 0,
        onlyNameOffsetY = 0,
        onlyNameWidth = 120,

        healthBarWidth = 1.1,
        healthBarHeight = 1.7,
        classColorEnemyPlates = false,
        classColorFriendlyPlates = false,
        healthTexture = "Interface\\TargetingFrame\\UI-StatusBar",
        shortenHealth = false,
        showHealthText = false,
        showHealthPercent = false,
        healthFont = "Fonts\\FRIZQT__.TTF",
        healthSize = 14,
        healthFlags = "OUTLINE",
        healthAnchor = "CENTER",
        healthRelAnchor = "CENTER",
        healthOffsetX = 0,
        healthOffsetY = 0,
        healthPercentSize = 12,
        healthPercentAnchor = "RIGHT",
        healthPercentRelAnchor = "RIGHT",
        healthPercentOffsetX = -2,
        healthPercentOffsetY = 0,

        showEnemyClassIcons = false,
        showFriendlyClassIcons = false,
        showEnemyTotemIcons = false,
        showFriendlyTotemIcons = false,
        iconSize = 40,
        totemIconSize = 30,
        iconAnchor = "BOTTOM",
        iconRelAnchor = "TOP",
        iconOffsetX = 0,
        iconOffsetY = 0,

        borderTexture = "Interface\\Buttons\\WHITE8X8",
        borderPadding = 1,
        borderThickness = 1,
        borderTargetColor = {1, 1, 1, 1},
        borderMouseoverColor = {0, 1, 1, 1},
        borderCombatColor = {1, 0, 0, 1},
        borderDefaultColor = {0, 0, 0, 1},

        threatHighColor = {0, 1, 0, 1},
        threatLowColor = {1, 0, 0, 1},
        threatAggroColor = {1, 1, 0, 1},

        showClassification = true,
        classificationSize = 25,
        classificationAnchor = "RIGHT",
        classificationRelAnchor = "LEFT",
        classificationOffsetX = -3,
        classificationOffsetY = 0,

        raidTargetAnchor = "LEFT",
        raidTargetRelAnchor = "RIGHT",
        raidTargetScale = 1.20,
        raidTargetOffsetX = 3,
        raidTargetOffsetY = 0,

        globalFrameScale = 1,
        targetFrameScale = 1.2,
        petFrameScale = 0.8,

        friendlyPlayerCastBar = true,
        enemyPlayerCastBar = true,
        friendlyNpcCastBar = false,
        enemyNpcCastBar = true,
        castBarTex = "Interface\\TargetingFrame\\UI-StatusBar",
        castBarFadeTime = 0.5,
        castBarHeight = 14,
        castBarWidth = 110,
        castBarShowIcon = true,
        castBarAnchor = "TOP",
        castBarRelativePoint = "BOTTOM",
        castBarOffsetX = 5,
        castBarOffsetY = 5,
        castBarColor = {1, 1, 0, 1},
        castBarSuccessColor = {0, 1, 0, 1},
        castBarFailedColor = {1, 0, 0, 1},
        castBarShieldColor = {0.5, 0.5, 1, 1},
        castBarBgColor = {0, 0, 0, 0.5},
        castNameFont = "Fonts\\FRIZQT__.TTF",
        castNameSize = 10,
        castNameWidth = 100,
        castNameFlags = "OUTLINE",
        castNameColor = {1, 1, 1, 1},
        castNameOffsetX = 0,
        castNameOffsetY = 0,
        castBarSparkWidth = 20,
        castBarSparkHeightMultiplier = 2,
        castBarIconSize = 15,
        castBarIconAnchor = "RIGHT",
        castBarIconRelAnchor = "LEFT",
        castBarIconOffsetX = 0,
        castBarIconOffsetY = 0
    }
}

standardProfiles = {
    ["PvP"] = {
        nameEnemyPlayerSize = 20,
        showEnemyClassIcons = true,
        showFriendlyClassIcons = false
    },
    ["PvE"] = {
        nameEnemyNpcSize = 16,
        showEnemyTotemIcons = true
    },
    ["Raid"] = {
        raidTargetScale = 1.5,
        showClassification = false
    }
}
